### PR TITLE
Rgb backlight

### PR DESCRIPTION
**Pull request by Wackerbarth**
You included RGB_Backlight.h twice.

You should also look at the BLINKM situation.  Generally, I don't like to see something included because of "A or B".  To me that indicates that there is really a reason, R, for the inclusion and that A->R and B->R rather than the inclusion being the direct result of either A or B.

### CODE REVIEW

**Comment by eboston** [comment]
Did you just merge my changes into development?  I hope not.  I wasn't 
ready for it to go in.  I was just asking if what I had was along the 
line of what you had in mind.

**Comment by eboston** [comment]
Never mind.  Didn't notice it was on my rep.  :)

**Comment by eboston** [comment]
I found the double include.  But what changes are you referring to in the second part?

**Comment by Wackerbarth** [comment]
Yep. you are certainly on the right track. Although there are some issues, I felt that a PR against your repo would be the easiest way to express what I was thinking.

I tried, perhaps unsuccessfully, to separate the generic RGB changes from the parts that belong to your personal configuration.

**Comment by Wackerbarth** [comment]
The issue with BLINKM.  Why does "BLINKM" cause the code to be included?  Does BLINKM have an RGB backlight, etc.

**Comment by eboston** [comment]
Only thing I am seeing in the commit is the other items about the stepper and stuff.  Other than the addition of the include at the bottom of the configuration.h file, those changes are for my testing.

In regards to BLINKM, it was already there and I didn't want to change existing functionality.  From what I read about it, it is a display with a color light around the rotary encoder.  What I am attempting to do is something similar.

**Comment by Wackerbarth** [comment]
The changes about the stepper, etc. are the result of your repo being a commit or two behind "Development". Other that that, and the double include, I didn't change anything except for indentation/whitespace.  But I do raise the question about BLINKM because I suspect that BLINKM should be defining HAS_RGB_BACKLIGHT (Perhaps with a different implementation as to which you alluded earlier)

**Comment by eboston** [comment]
Like I said, it was already there and I don't like changing code I can't test.  

About being a commit or two behind Development, I see a message about my Development being behind, but when I do a compare between the two branches, it doesn't show any differences.  Obviously, I am doing something wrong, but not sure what.

**Comment by eboston** [comment]
Was finally able to get the new stuff in Development merged in.  Was comparing in the wrong order.

**Pull request merged**
